# Idea behind the Algorithm

All the parts are somewhat straight forward and does not need an explaination due to the generalization of **SA algorithm**, the main difference in using this algorithm for different problems is in `purturbation` function. Here in **QAP**, where the solution is in the form of a **permutation**, **neighbors** of a permutation can be considered the permutations that can be obtained from the base by swapping two elements. `perturbation` function chooses two random index and swaps them to make a new neighboring solution as the rest is the same for all SA-based searches

# Setup

In [1]:
import random
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

# Loading Data

In [2]:
def load_data(filename) :

    f = open(filename, "r")
    lines = f.readlines()

    n = int(lines[0])

    dist = []
    for i in range(n) : 
        dist.append(list(map(int, lines[i + 2].split())))

    flow = []
    for i in range(n) :
        flow.append(list(map(int, lines[n + 2 + i + 2 - 1].split())))

    return n, np.array(dist), np.array(flow)


# Simulated Annealing

In [14]:
def Energy(sol) : 
    global dist, flow
    return np.sum(flow * dist[np.ix_(sol,sol)])

In [17]:
def perturbation(sol) : 
    new_sol = sol.copy()
    i = random.randrange(len(sol))
    j = random.randrange(len(sol))

    new_sol[i], new_sol[j] = new_sol[j], new_sol[i]
    return new_sol

In [30]:
def acceptance(delta_E, T) : 
    if(delta_E < 0) : 
        return True
    
    r = random.random()
    if(r < np.exp(-delta_E/T)) : 
        return True

    return False

In [133]:
def SA(n, dist, flow, epoch = 100, alpha = 0.99, Tmax = 10000, Tmin = 0.001) : 
    bst = 5000000
    bst_sol = np.random.permutation(n)

    for _ in range(epoch) : 
        T = Tmax
        sol = np.random.permutation(n)
        E = Energy(sol)

        while(T > Tmin) :
            sol_new = perturbation(sol)
            E_new = Energy(sol_new)

            delta_E = E_new - E

            if(acceptance(delta_E, T)) : 
                sol = sol_new
                E = E_new
            
            T *= alpha
        
        if(E < bst) : 
            bst = E
            bst_sol = sol
            
    return (bst, bst_sol)

# 1. chr12a

In [124]:
n, dist, flow = load_data("chr12a.dat")

In [125]:
print(n)
print(dist)
print(flow)

12
[[ 0 90 10 23 43  0  0  0  0  0  0  0]
 [90  0  0  0  0 88  0  0  0  0  0  0]
 [10  0  0  0  0  0 26 16  0  0  0  0]
 [23  0  0  0  0  0  0  0  0  0  0  0]
 [43  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 88  0  0  0  0  0  0  1  0  0  0]
 [ 0  0 26  0  0  0  0  0  0  0  0  0]
 [ 0  0 16  0  0  0  0  0  0 96  0  0]
 [ 0  0  0  0  0  1  0  0  0  0 29  0]
 [ 0  0  0  0  0  0  0 96  0  0  0 37]
 [ 0  0  0  0  0  0  0  0 29  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 37  0  0]]
[[ 0 36 54 26 59 72  9 34 79 17 46 95]
 [36  0 73 35 90 58 30 78 35 44 79 36]
 [54 73  0 21 10 97 58 66 69 61 54 63]
 [26 35 21  0 93 12 46 40 37 48 68 85]
 [59 90 10 93  0 64  5 29 76 16  5 76]
 [72 58 97 12 64  0 96 55 38 54  0 34]
 [ 9 30 58 46  5 96  0 83 35 11 56 37]
 [34 78 66 40 29 55 83  0 44 12 15 80]
 [79 35 69 37 76 38 35 44  0 64 39 33]
 [17 44 61 48 16 54 11 12 64  0 70 86]
 [46 79 54 68  5  0 56 15 39 70  0 18]
 [95 36 63 85 76 34 37 80 33 86 18  0]]


In [123]:
SA(n, dist, flow)

(9552, array([ 4,  3,  5, 11,  1,  9,  0, 10,  6,  8,  7,  2]))

# 2. esc32a

In [126]:
n, dist, flow = load_data("esc32a.dat")

In [127]:
SA(n, dist, flow)

(144,
 array([13, 20,  9, 23, 14, 17, 21, 18, 31, 22,  6, 15,  8,  7, 24, 26,  1,
        30,  0, 28,  2, 19, 12, 10,  4, 29, 11, 25,  3, 27,  5, 16]))

# 3. nug20

In [135]:
n, dist, flow = load_data("nug20.dat")

In [136]:
SA(n, dist, flow)

(2580,
 array([ 1, 18, 16,  9,  6,  0,  2,  8, 15, 11,  7, 12,  5, 17, 13, 10,  4,
        19, 14,  3]))

# 4. tai30a

In [137]:
n, dist, flow = load_data("tai30a.dat")

In [138]:
SA(n, dist, flow)

(1859256,
 array([19,  2, 17,  7, 25, 15,  9,  1, 29, 16, 10, 24, 22,  3, 14, 28, 27,
        23, 11, 13,  8, 20,  5, 21,  4,  6, 18, 12, 26,  0]))

# 5. lipa50a

In [140]:
n, dist, flow = load_data("lipa50a.dat")

In [141]:
SA(n, dist, flow)

(62914,
 array([23, 33,  2, 45, 43, 47,  8, 13, 40,  4, 21, 35,  0, 31, 11, 20, 39,
        44, 18, 30,  3,  6, 15,  9, 26, 41, 37,  7, 10, 49, 48, 12, 42, 14,
        27, 22, 32,  5, 46,  1, 28, 25, 17, 29, 34, 16, 36, 38, 19, 24]))